# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z43N9pQ2Fus71VBmMVTdiBRciONcuZhD
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

names=['sepel-length', 'sepel-width', 'petal-length', 'patel-width', 'Class']

dataset = pd.read_csv(url, names=names)

dataset.head()

dataset['Class'].value_counts()

dataset.shape

dataset.info()

X=dataset.iloc[:,:4]

X.head()

y=dataset.iloc[:,-1]

y.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

from sklearn.neighbors import KNeighborsClassifier

knnmodel = KNeighborsClassifier(n_neighbors=3)
knnmodel.fit(X_train, y_train)
y_predict1 = knnmodel.predict(X_test)
y_predict1

from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test.values, y_predict1)

acc

